# Generated by Django 5.1 on 2024-11-03 19:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='N/A', max_length=100)),
                ('hotel_photos', models.FileField(blank=True, help_text='Upload an image file', null=True, upload_to='hotel_photos/', verbose_name='Hotel Photos')),
                ('phone_number', models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+19999999999'. It must have 10 digits after the country code.", regex='^\\+?1?\\d{10}$')], verbose_name='Phone Number')),
                ('description', models.TextField(blank=True, verbose_name='General Hotel Description')),
                ('facilities', models.TextField(blank=True, help_text='Comma-separated list of facilities, e.g., Wi-Fi, Pool, Parking', verbose_name='Facilities')),
                ('check_in_time', models.TimeField(default='15:00', verbose_name='Check-in Time')),
                ('check_out_time', models.TimeField(default='11:00', verbose_name='Check-out Time')),
                ('cancellation_policy', models.TextField(blank=True, verbose_name='Cancellation Policy')),
                ('student_discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount for students', max_digits=5, verbose_name='Student Discount (%)')),
                ('special_offers', models.CharField(blank=True, max_length=255, verbose_name='Special Offers')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Average Rating')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rate between 1 to 5 stars', verbose_name='Rating')),
                ('review', models.TextField(blank=True, verbose_name='Review')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to='student.student')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=255, verbose_name='Room Type')),
                ('number_of_rooms', models.IntegerField(verbose_name='Number of Rooms')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per Night (USD)')),
                ('facilities', models.TextField(help_text='Comma-separated list of room facilities, e.g., Wi-Fi, TV, Mini-bar, Sea View', verbose_name='Room Facilities')),
                ('breakfast_included', models.BooleanField(default=False, verbose_name='Breakfast Included')),
                ('room_size', models.CharField(blank=True, max_length=50, verbose_name='Room Size (e.g., 30 sqm)')),
                ('max_occupancy', models.IntegerField(blank=True, help_text='Number of guests allowed', null=True, verbose_name='Maximum Occupancy')),
                ('smoking_allowed', models.BooleanField(default=False, verbose_name='Smoking Allowed')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('expected_arrival_time', models.TimeField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], default='card', max_length=50)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('canceled', models.BooleanField(default=False)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='student.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel.roomsdescription')),
            ],
        ),
    ]
