# Generated by Django 5.1 on 2024-11-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_reservation_total_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
