# Generated by Django 5.1 on 2024-11-10 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_reservation_expected_arrival_time'),
        ('student', '0002_student_favorite_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to='hotel.roomsdescription'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reservations', to='student.student'),
        ),
    ]
