# Generated by Django 5.1 on 2024-11-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_reservation_hotel_alter_reservation_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreviews',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rate between 1 to 5 stars', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='review',
            field=models.TextField(blank=True, default='', verbose_name='Review'),
        ),
    ]
