# Generated by Django 5.1 on 2024-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_customerreviews_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address1',
            field=models.TextField(default=0, verbose_name='Address1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='address2',
            field=models.TextField(default=1, verbose_name='Address2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='zip',
            field=models.IntegerField(default=11201),
            preserve_default=False,
        ),
    ]
