# Generated by Django 5.1 on 2024-12-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_hotel_address_remove_hotel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tourist_spots',
            field=models.JSONField(default=list),
        ),
    ]
