# Generated by Django 5.1 on 2024-12-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_hotel_latitude_hotel_longitude_hotel_tourist_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='Address2'),
        ),
    ]
