# Generated by Django 5.1 on 2024-12-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_hotel_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('succeeded', 'succeeded'), ('failed', 'failed')], default='failed', max_length=20),
        ),
    ]
