# Generated by Django 4.2.16 on 2024-12-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_reservation_room_reservation_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rooms',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to='hotel.roomsdescription'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FinalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('payment_status', models.CharField(choices=[('succeeded', 'succeeded'), ('failed', 'failed')], default='failed', max_length=20)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to='hotel.reservation')),
            ],
        ),
    ]
