# Generated by Django 4.2.16 on 2024-12-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_remove_reservation_rooms_reservation_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FinalReservation',
        ),
    ]
