# Generated by Django 4.2.16 on 2024-12-10 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_reservation_amount_delete_finalreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('succeeded', 'succeeded'), ('failed', 'failed')], default='failed', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to='hotel.finalreservation'),
        ),
    ]
