# Generated by Django 4.2.16 on 2024-12-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_finalreservation_reservation_reservation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_id',
            new_name='reservation',
        ),
    ]
