# Generated by Django 5.1 on 2024-09-23 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_average_rating_alter_hotel_facilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rate between 1 to 5 stars', verbose_name='Rating')),
                ('review', models.TextField(blank=True, verbose_name='Review')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel.hotel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=255, verbose_name='Room Type')),
                ('number_of_rooms', models.IntegerField(verbose_name='Number of Rooms')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per Night (USD)')),
                ('facilities', models.TextField(help_text='Comma-separated list of room facilities, e.g., Wi-Fi, TV, Mini-bar, Sea View', verbose_name='Room Facilities')),
                ('breakfast_included', models.BooleanField(default=False, verbose_name='Breakfast Included')),
                ('room_size', models.CharField(blank=True, max_length=50, verbose_name='Room Size (e.g., 30 sqm)')),
                ('max_occupancy', models.IntegerField(blank=True, help_text='Number of guests allowed', null=True, verbose_name='Maximum Occupancy')),
                ('smoking_allowed', models.BooleanField(default=False, verbose_name='Smoking Allowed')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel')),
            ],
        ),
    ]
