# Generated by Django 5.1 on 2024-11-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reservation_damage_insurance_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_hotels',
            field=models.ManyToManyField(blank=True, related_name='favorite_students', to='hotel.hotel'),
        ),
    ]
