# Generated by Django 5.1 on 2024-09-28 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+19999999999'. It must have 10 digits after the country code.", regex='^\\+?1?\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
