name: Django CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Modify path if requirements.txt is in a subfolder

      - name: Run Tests
        run: |
          cd backend
          python manage.py test --noinput

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo yum -y install jq
          curl -O https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
          unzip awscli-exe-linux-x86_64.zip
          sudo ./aws/install
          curl -Lo eb.zip https://s3.amazonaws.com/elasticbeanstalk-cli-resources/releases/EBCLI-3.20.0/EBCLI-3.20.0.zip
          unzip eb.zip -d ~/.ebcli
          pip install -r ~/.ebcli/requirements.txt
          export PATH=~/.ebcli:$PATH

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd backend  # Navigate to backend if your application resides in a subfolder
          eb init campusvacay --platform "Python 3.12 running on 64bit Amazon Linux 2023" --region us-east-1
          eb use Campusvacay-env  # Use your environment name
          eb deploy
