name: Django CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Modify path if requirements.txt is in a subfolder

      - name: Run Tests
        run: |
          cd backend
          python manage.py test  # Modify path if manage.py is in a subfolder
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9, 3.11, 3.12'  # Use the version compatible with your EC2 deployment

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Deploy to EC2
        env:
          #DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          #ENV_VARIABLES: ${{ secrets.ENV_VARIABLES }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          # Connect to EC2 and deploy
          ssh -i ${{ secrets.PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Connecting to EC2 and deploying application..."

            # Navigate to your project directory on the EC2 instance
            cd Software-Engineering-1-CampusVacay/backend  # Replace with the actual path

            # Pull latest code
            git pull origin main

            # Activate virtual environment
            source env/bin/activate

            # Install any new dependencies
            pip install -r requirements.txt

            # Apply migrations
            python manage.py migrate

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart Gunicorn and Nginx
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
